spring:
  application:
    name: "wait-and-smile"

  datasource:
    url: jdbc:sqlite:./data/waitlist.db
    driver-class-name: org.sqlite.JDBC
    username: ''
    password: ''

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:

            scope:
              - openid
              - profile
              - email

  mail:
    host: smtp.gmail.com
    port: 587
    username: info@vibio.co
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
